import 'dart:convert';

class Bookmark {
  final int? bookmarkId;           // Generated by database (identity)
  final String userId;             // User who owns the bookmark
  final String placeId;            // Google Place ID
  final String placeName;          // Display name
  final String placeAddress;       // Formatted address
  final double placeLatitude;      // Geographic coordinate
  final double placeLongitude;     // Geographic coordinate
  final double? placeRating;       // Google rating
  final String? placeTypes;        // Comma-separated types
  final String? placePhotoRef;     // Google photo reference
  final String? placePhone;        // Phone number
  final String? placeWebsite;      // Website URL
  final Map<String, dynamic>? placeRegularOpeningHours; // JSONB
  final int? placePriceLevel;      // Price level (0-4)
  final String? notes;             // User's personal notes
  final DateTime? createdAt;       // Timestamp when bookmarked

  const Bookmark({
    this.bookmarkId,
    required this.userId,
    required this.placeId,
    required this.placeName,
    required this.placeAddress,
    required this.placeLatitude,
    required this.placeLongitude,
    this.placeRating,
    this.placeTypes,
    this.placePhotoRef,
    this.placePhone,
    this.placeWebsite,
    this.placeRegularOpeningHours,
    this.placePriceLevel,
    this.notes,
    this.createdAt,
  });

  // ─── Copy with ──────────────────────────────────────────────

  Bookmark copyWith({
    int? bookmarkId,
    String? userId,
    String? placeId,
    String? placeName,
    String? placeAddress,
    double? placeLatitude,
    double? placeLongitude,
    double? placeRating,
    String? placeTypes,
    String? placePhotoRef,
    String? placePhone,
    String? placeWebsite,
    Map<String, dynamic>? placeRegularOpeningHours,
    int? placePriceLevel,
    String? notes,
    DateTime? createdAt,
  }) {
    return Bookmark(
      bookmarkId: bookmarkId ?? this.bookmarkId,
      userId: userId ?? this.userId,
      placeId: placeId ?? this.placeId,
      placeName: placeName ?? this.placeName,
      placeAddress: placeAddress ?? this.placeAddress,
      placeLatitude: placeLatitude ?? this.placeLatitude,
      placeLongitude: placeLongitude ?? this.placeLongitude,
      placeRating: placeRating ?? this.placeRating,
      placeTypes: placeTypes ?? this.placeTypes,
      placePhotoRef: placePhotoRef ?? this.placePhotoRef,
      placePhone: placePhone ?? this.placePhone,
      placeWebsite: placeWebsite ?? this.placeWebsite,
      placeRegularOpeningHours: placeRegularOpeningHours ?? this.placeRegularOpeningHours,
      placePriceLevel: placePriceLevel ?? this.placePriceLevel,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  // ─── To/From Map (SQLite) ──────────────────────────────────

  Map<String, dynamic> toMap() {
    return {
      'bookmark_id': bookmarkId,
      'user_id': userId,
      'place_id': placeId,
      'place_name': placeName,
      'place_address': placeAddress,
      'place_latitude': placeLatitude,
      'place_longitude': placeLongitude,
      'place_rating': placeRating,
      'place_types': placeTypes,
      'place_photo_ref': placePhotoRef,
      'place_phone': placePhone,
      'place_website': placeWebsite,
      'place_regular_opening_hours': placeRegularOpeningHours != null
          ? jsonEncode(placeRegularOpeningHours)
          : null,
      'place_price_level': placePriceLevel,
      'notes': notes,
      'created_at': createdAt?.toIso8601String(),
    };
  }

  factory Bookmark.fromMap(Map<String, dynamic> map) {
    return Bookmark(
      bookmarkId: map['bookmark_id'] as int?,
      userId: map['user_id'] as String,
      placeId: map['place_id'] as String,
      placeName: map['place_name'] as String,
      placeAddress: map['place_address'] as String,
      placeLatitude: (map['place_latitude'] as num).toDouble(),
      placeLongitude: (map['place_longitude'] as num).toDouble(),
      placeRating: map['place_rating']?.toDouble(),
      placeTypes: map['place_types'] as String?,
      placePhotoRef: map['place_photo_ref'] as String?,
      placePhone: map['place_phone'] as String?,
      placeWebsite: map['place_website'] as String?,
      placeRegularOpeningHours: map['place_regular_opening_hours'] != null
          ? jsonDecode(map['place_regular_opening_hours'] as String)
          : null,
      placePriceLevel: map['place_price_level'] as int?,
      notes: map['notes'] as String?,
      createdAt: map['created_at'] != null
          ? DateTime.parse(map['created_at'] as String)
          : null,
    );
  }

  // ─── To/From JSON (Supabase) ───────────────────────────────

  Map<String, dynamic> toJson() {
    return {
      'bookmark_id': bookmarkId,
      'user_id': userId,
      'place_id': placeId,
      'place_name': placeName,
      'place_address': placeAddress,
      'place_latitude': placeLatitude,
      'place_longitude': placeLongitude,
      'place_rating': placeRating,
      'place_types': placeTypes,
      'place_photo_ref': placePhotoRef,
      'place_phone': placePhone,
      'place_website': placeWebsite,
      'place_regular_opening_hours': placeRegularOpeningHours,
      'place_price_level': placePriceLevel,
      'notes': notes,
      'created_at': createdAt?.toIso8601String(),
    };
  }

  factory Bookmark.fromJson(Map<String, dynamic> json) {
    return Bookmark(
      bookmarkId: json['bookmark_id'] as int?,
      userId: json['user_id'] as String,
      placeId: json['place_id'] as String,
      placeName: json['place_name'] as String,
      placeAddress: json['place_address'] as String,
      placeLatitude: (json['place_latitude'] as num).toDouble(),
      placeLongitude: (json['place_longitude'] as num).toDouble(),
      placeRating: json['place_rating']?.toDouble(),
      placeTypes: json['place_types'] as String?,
      placePhotoRef: json['place_photo_ref'] as String?,
      placePhone: json['place_phone'] as String?,
      placeWebsite: json['place_website'] as String?,
      placeRegularOpeningHours: json['place_regular_opening_hours'] as Map<String, dynamic>?,
      placePriceLevel: json['place_price_level'] as int?,
      notes: json['notes'] as String?,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
    );
  }
}